# Generated by Django 5.1.7 on 2025-04-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["last_name"],
                "permissions": [("can_block_user", "Can block user"), ("can_unblock_user", "Can unblock user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
