# Generated by Django 5.1.7 on 2025-03-26 16:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Текст письма"),
        ),
    ]
