# Generated by Django 5.1.7 on 2025-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_message_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Текст письма"),
        ),
    ]
