# Generated by Django 5.1.7 on 2025-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_ended_date_alter_mailing_started_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="response_mail_server",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера"),
        ),
    ]
