# Generated by Django 5.1.7 on 2025-03-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailingattempt_response_mail_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="ended_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="started_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первой отправки"),
        ),
    ]
