# Generated by Django 5.1.7 on 2025-04-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_recipient_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["pk"], "verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["pk"], "verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["pk"],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
