# Generated by Django 5.1.7 on 2025-04-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_mailingattempt_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["pk"],
                "permissions": [
                    ("can_disable_mailing", "Can disable Mailing"),
                    ("can_enable_mailing", "Can enable Mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
