# Generated by Django 5.1.7 on 2025-04-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="send_messages",
            field=models.PositiveIntegerField(default=0, verbose_name="Отправлено сообщений"),
        ),
    ]
